export const saveProduct = async (product) => {
  try {
    console.log("Save Product");
  } catch (error) {
    console.error("Error while saving product!", error);
  }
};
